services:
  grafana:
    user: root
    container_name: 'carboncloud-cclogs-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.0.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/carboncloud-cclogs-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/carboncloud-cclogs-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.carboncloud-cclogs-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: carboncloud-cclogs-panel
      GF_USERS_DEFAULT_THEME: light
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource

    network_mode: 'host'
